export enum ActionType {
  LOGIN_FAILURE = "LOGIN_FAILURE",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGOUT = "LOGOUT",
  AUTH_ERROR = "AUTH_ERROR",
  USER_LOADED = "USER_LOADED",
  USER_LOADING = "USER_LOADING",
  CLEAR_ALL = "CLEAR_ALL",
  ERROR_MESSAGE = "ERROR_MESSAGE",
}
